DEFAULT_OPEN_AI_URL = "http://localhost:1234/v1"
DEFAULT_AI_TOKEN = "lm-studio"
DEFAULT_MODEL = "qwen/qwen3-vl-4b"
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TEMPERATURE = 0.7

ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
